version: 2
jobs:
  build:
    docker:
      - image: cypress/base


    working_directory: ~/cypress-todomvc

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install cypress --save-dev
      - run: npm install wait-on --save-dev
      - run: npm install --save-dev

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm start
      - run: npx cypress run