version: 2
jobs:
  build:
    docker:
      - image: circleci/node11.1.0


    working_directory: ~/cypress-todomvc

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm start & wait-on http://localhost:8080
      - run: npx cypress run